### ISSUE TITLE
feature request: Tabbyml support

### ISSUE THREAD

**Issue by Kamilcuk** [tzachar/cmp-ai#21]
[Tabbyml](https://github.com/TabbyML/tabby) is an self-hosted AI, with OpenAI deprecated completion similar API: https://tabby.tabbyml.com/api/completion/ , but with a few modifications.

Difference vs OpenAI for starters is:
- custom URL
- custom autnentication token passed to authorization: bearer

Then there are also different paramters for completions api, like git_url or declarations, that would be nice to also provide for tabby.

I believe an initial version should be easy to implement. I'll maybe sit down to it, depending on the time.

Thanks.

**Comment by tzachar** [comment]
Would gladly accept new PRs for additional sources.
