### ISSUE TITLE
Settings for own LLM server

### ISSUE THREAD

**Issue by Alpensin** [tzachar/cmp-ai#23]
In our company we have our own LLM servers. I didn't find it in readme, is it possible to set custom url of the server?

**Comment by tzachar** [comment]
Not support as of now.
The api endpoint is hardcoded in each source.
If you are willing to create a PR, you can pull the url out into a config option, which, if not set, defaults to the hardcoded one.

**Comment by Alpensin** [comment]
See in code, that BASE_URL is hardcoded. It will be great to move it to config. Maybe get it from environment variables.

**Comment by tzachar** [comment]
See my comment above.
If you want this, go ahead and implement it ;-)
I'll promptly merge such a PR.
