### ISSUE TITLE
Bard Error: json.choices returns nil instead of table

### ISSUE THREAD

**Issue by mystilleef** [tzachar/cmp-ai#3]
I'm trying to use the `Bard` backend with `cmp-ai` but I'm getting the error in the screenshot below.

![Screenshot from 2023-06-20 05-50-43](https://github.com/tzachar/cmp-ai/assets/273399/8b0858a5-e7ba-4a01-be08-4e0b7af1aa80)

Just to make sure it's not a problem with my `Bard` API installation, I can successfully call the `Bard` API from a Python `REPL` as you can see in the screenshot below.

![Screenshot from 2023-06-20 06-05-12](https://github.com/tzachar/cmp-ai/assets/273399/d2081d2d-b3aa-467b-8185-a178892bb7b5)

The culprit seems to be `json.choices` returning `nil` instead of a table on `line 83` in the bard backend.

Let me know if you need me to provide further details.

**Comment by mystilleef** [comment]
It's fixed. However, I can't get any completion suggestions from Bard. Maybe I have to be in the right context for it to work. Back to copilot, lsp, and treesitter for now.

**Comment by tzachar** [comment]
try to update your api key.
