### ISSUE TITLE
Configuring notifications

### ISSUE THREAD

**Issue by andy941** [tzachar/cmp-ai#34]
Hi great plugin!

I find the notifications too cluttering but I would like to keep the feedback they provide on the model background execution (I use Ollama).

I use Noice and it has a great way to handle LSP progress information using mini.nvim and I am trying to replicate that but can't get it to work just by changing the notify callback in the cmp_ai config. Could you help me?

Thanks,
 Andrea

**Comment by tzachar** [comment]
try installing a plugin which plugs into `vim.notify`
you can try [nvim-notify](https://github.com/rcarriga/nvim-notify)

**Comment by andy941** [comment]
My point is that I can modify the nvim-notify callback but it's still very cluttering. I think such notifications are much better suited for the mini.nvim style but I am not sure how to adapt the nvim-notify example from the default config to achieve that.

**Comment by tzachar** [comment]
Not familiar with mini.nvim's style.
Can't help you there.
