### ISSUE TITLE
Add delay when firing auto-complete

### ISSUE THREAD

**Issue by JoseConseco** [tzachar/cmp-ai#9]
I wish user could define delay e.g. 0.3 sec,  where  cmp-ai would wait for user to be idle for 0.3 before sending request to server. 
I think right now it fires autocomplete on every stroke, right? 
I know about [C-x] mapping, but still  having delay option would be cool - it would prevent my GPU fans from spining when typing fast, and not waiting for autocomplete.

**Comment by tzachar** [comment]
This would be a request for upstream cmp (I think you can already achieve something similar using the general cmp config).
You can also disable the 'autocomplete on every keystroke' in the config. just set `run_on_every_keystroke` to `false`.

**Comment by JoseConseco** [comment]
I  tried debounce option in cmp  ,  would still trigger  cmp_ai completions few times in a row ( disabling `run_on_every_keystroke' helps but there are still to many triggers for cmpletions).

In any case I just finished implementing debounce for cmp_ai,  if you want I can make PR, but I would need help with how to expose this in  cmp_ai settings. 
My code is based on [this](https://github.com/runiq/neovim-throttle-debounce?tab=readme-ov-file#debouncing-on-the-trailing-edge).

Changed source.lua lines: 
```lua
function Source:trigger(ctx, callback)
  if vim.fn.mode() == 'i' then
    self:_do_complete(ctx, callback)
  end
end

-- based on https://github.com/runiq/neovim-throttle-debounce/blob/main/lua/throttle-debounce/init.lua (MIT)
local function debounce_trailing(fn, ms)
    local timer = vim.loop.new_timer()
    local wrapped_fn

    function wrapped_fn(...)
      local argv = {...}
      local argc = select('#', ...)
      -- timer:stop() -- seems not needed?
      timer:start(ms, 0, function()
        pcall(vim.schedule_wrap(fn), unpack(argv, 1, argc))
      end)
    end
    return wrapped_fn, timer
end

local bounce_time = 700 -- in ms
local bounced_complete, ret_tim =  debounce_trailing(
  Source.trigger,
  bounce_time)


-- on keypress event autocommand -  call tim.timer_again
local au_bound = vim.api.nvim_create_augroup("BounceCompletion", { clear = true })
vim.api.nvim_create_autocmd("TextChangedI",{
  pattern = "*",
  callback = function()
    vim.loop.timer_again(ret_tim)
  end,
  group = au_bound
})

--- complete
function Source:complete(ctx, callback)
  if conf:get('ignored_file_types')[vim.bo.filetype] then
    callback()
    return
  end
  -- local bufnr = vim.api.nvim_get_current_buf()
  bounced_complete(self, ctx, callback)

end         
```
@tzachar
